# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joseph/RPdev/Tracking360

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joseph/RPdev/Tracking360

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joseph/RPdev/Tracking360/CMakeFiles /home/joseph/RPdev/Tracking360/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joseph/RPdev/Tracking360/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tracking360

# Build rule for target.
Tracking360: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tracking360
.PHONY : Tracking360

# fast build rule for target.
Tracking360/fast:
	$(MAKE) -f CMakeFiles/Tracking360.dir/build.make CMakeFiles/Tracking360.dir/build
.PHONY : Tracking360/fast

Motion.o: Motion.cpp.o
.PHONY : Motion.o

# target to build an object file
Motion.cpp.o:
	$(MAKE) -f CMakeFiles/Tracking360.dir/build.make CMakeFiles/Tracking360.dir/Motion.cpp.o
.PHONY : Motion.cpp.o

Motion.i: Motion.cpp.i
.PHONY : Motion.i

# target to preprocess a source file
Motion.cpp.i:
	$(MAKE) -f CMakeFiles/Tracking360.dir/build.make CMakeFiles/Tracking360.dir/Motion.cpp.i
.PHONY : Motion.cpp.i

Motion.s: Motion.cpp.s
.PHONY : Motion.s

# target to generate assembly for a file
Motion.cpp.s:
	$(MAKE) -f CMakeFiles/Tracking360.dir/build.make CMakeFiles/Tracking360.dir/Motion.cpp.s
.PHONY : Motion.cpp.s

PCA9685Driver.o: PCA9685Driver.c.o
.PHONY : PCA9685Driver.o

# target to build an object file
PCA9685Driver.c.o:
	$(MAKE) -f CMakeFiles/Tracking360.dir/build.make CMakeFiles/Tracking360.dir/PCA9685Driver.c.o
.PHONY : PCA9685Driver.c.o

PCA9685Driver.i: PCA9685Driver.c.i
.PHONY : PCA9685Driver.i

# target to preprocess a source file
PCA9685Driver.c.i:
	$(MAKE) -f CMakeFiles/Tracking360.dir/build.make CMakeFiles/Tracking360.dir/PCA9685Driver.c.i
.PHONY : PCA9685Driver.c.i

PCA9685Driver.s: PCA9685Driver.c.s
.PHONY : PCA9685Driver.s

# target to generate assembly for a file
PCA9685Driver.c.s:
	$(MAKE) -f CMakeFiles/Tracking360.dir/build.make CMakeFiles/Tracking360.dir/PCA9685Driver.c.s
.PHONY : PCA9685Driver.c.s

Scheduler.o: Scheduler.cpp.o
.PHONY : Scheduler.o

# target to build an object file
Scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/Tracking360.dir/build.make CMakeFiles/Tracking360.dir/Scheduler.cpp.o
.PHONY : Scheduler.cpp.o

Scheduler.i: Scheduler.cpp.i
.PHONY : Scheduler.i

# target to preprocess a source file
Scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/Tracking360.dir/build.make CMakeFiles/Tracking360.dir/Scheduler.cpp.i
.PHONY : Scheduler.cpp.i

Scheduler.s: Scheduler.cpp.s
.PHONY : Scheduler.s

# target to generate assembly for a file
Scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/Tracking360.dir/build.make CMakeFiles/Tracking360.dir/Scheduler.cpp.s
.PHONY : Scheduler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Tracking360"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Motion.o"
	@echo "... Motion.i"
	@echo "... Motion.s"
	@echo "... PCA9685Driver.o"
	@echo "... PCA9685Driver.i"
	@echo "... PCA9685Driver.s"
	@echo "... Scheduler.o"
	@echo "... Scheduler.i"
	@echo "... Scheduler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

